server:
  port: 9000

logging:
  level:
    root: DEBUG
    com.binchencoder.spring: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: DEBUG